### PR TITLE
add attestations as allowed permission

### PR DESCRIPTION
**Pull request by bdehamer**
Updates the list of recognized permissions to include the new `attestations` permission (see [Using artifact attestations to establish provenance for builds](https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds))

### CODE REVIEW

**Review by rhysd — APPROVED** [review]
Thank you for catching this.

**Comment by martincostello** [comment]
When's the next planned stable release that will contain this change?

**Comment by rhysd** [comment]
I can't promise it (since the next release will be bigger than usual), but I will make the new release by the end of this week (in JST).

**Comment by rhysd** [comment]
I apologize for the delay but I needed more time than expected to implement some feature and some workaround. Now I released a new version v1.7.0 tonight. https://github.com/rhysd/actionlint/releases/tag/v1.7.0

**Pull request merged**
