### PR TITLE
Add `macos-15` runner label support

### PR DESCRIPTION
**Pull request by muzimuzhi**
This PR is based on the head of #451.

I didn't add `macos-15-xl` as it's unknown whether it's supported or not.

### CODE REVIEW

**Comment by rhysd** [comment]
It seems that macos-15 runner is not GA yet. Do you know any official documentation mentioning macos-15 runner?

https://github.com/github/roadmap/issues/986

**Comment by rhysd** [comment]
I found the official resource: https://github.com/actions/runner-images?tab=readme-ov-file#available-images

This PR sounds good to be merged.

> I didn't add macos-15-xl as it's unknown whether it's supported or not.

It is not documented in the above document. So let's not include it for now.

**Comment by muzimuzhi** [comment]
> It seems that macos-15 runner is not GA yet.

Yes. It's just in public beta.
https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

> > I didn't add macos-15-xl as it's unknown whether it's supported or not.
> 
> It is not documented in the above document. So let's not include it for now.

Actually none of the `macos-<n>-xl` labels are listed in https://github.com/actions/runner-images?tab=readme-ov-file#available-images.

"Good news" is that it's announced that `macos-12-xl`, `macos-13-xl`, and `macos-13-xl-arm64` will be deprecated on Dec 3, 2024.
https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

**Review by rhysd — APPROVED** [review]
Thanks. Looks good.

**Pull request merged**
