### PR TITLE
Changes to make actionlint usable when using it as a library

### PR DESCRIPTION
**Pull request by hugo-syn**
I've added a constructor for _RuleBase_ and changed _error_ and _errorf_ from private to public, otherwise It's not possible to create new rules. I hope that this is the best option, if not, how should we create new rules when using _actionlint_ as a library ? 

I also changed _wait_ from private to public in _process.go_.

### CODE REVIEW

**Comment by rhysd** [comment]
What is the reason to make these APIs public? Especially, `RuleBase` is a base type for existing rules so it is unnecessarily public if you just use the rules. Do you make your own rules?

**Comment by hugo-syn** [comment]
Yes I would like to make my own rules

**Review by rhysd — CHANGES_REQUESTED** [review]

**Comment by hugo-syn** [comment]
I was actually reimplementing my own Linter to run my custom rules, because I don't want all the rules, so I just need to access the _RuleBase_ and the methods _error_ and _errorf_ to create new rules

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
OK. But please note that you can filter out errors from specific rules by `-ignore`.

**Comment by rhysd** [comment]
I added `OnRulesCreated` hook API at  https://github.com/rhysd/actionlint/commit/655d745419ce1cf2cdf94d1ddf613c8cf14dfdde.

You can add/remove rules without reimplementing `check` method.

```go
o := &LinterOptions{
    OnRulesCreated: func(rules []Rule) []Rule {
        // Remove 'runner-label' rule
        for i, r := range rules {
            if r.Name() == "runner-label" {
                rules = append(rules[:i], rules[i+1:]...)
                break
            }
        }
        // Add your own rule
        rules = append(rules, NewYourOwnRule())
        return rules
    },
}
```

So you no longer need to reimplement `Linter.check` only for adding/removing rules. With this API, can the `ConcurrentProcess` API be back to private since you no longer need to call `NewRuleShellcheck` by yourself?

I'd like to keep the API private since it is an implementation detail and can be updated on patch releases.

**Comment by hugo-syn** [comment]
Sounds nice, I think that I don't need to re-implement my linter now, thanks :)

**Comment by rhysd** [comment]
Great. Thank you for confirming that. I'll revert `ConcurrentProcess` to `concurrentProcess`

**Pull request merged**
