### PR TITLE
change language of .pre-commit-hooks.yaml to golang

### PR DESCRIPTION
**Pull request by Freed-Wu**
Refer <https://github.com/scop/pre-commit-shfmt/blob/main/.pre-commit-hooks.yaml>

### CODE REVIEW

**Comment by dokempf** [comment]
Actually, this does not work straight away, as @adamchainz noted in #297 . I found a solution on my fork that works: https://github.com/dokempf/actionlint/commit/691f4ee697dca41cc1481ee03fc43b2d35f20f98

**Comment by Freed-Wu** [comment]
What is your enviroment? This is mine:
```shell
$ go version
go version go1.20.4 linux/amd64
$ uname -r
6.3.2-arch1-1
```

**Comment by Freed-Wu** [comment]
If I uninstalled go, I'll get

```
An unexpected error has occurred: CalledProcessError: command: ('go', 'install', './...')
return code: 1
expected return code: 0
stdout:
    Executable `go` not found
```

Can you install go to validate again?

**Comment by rhysd** [comment]
I'm not a user of pre-commit. So I'm not familiar with the tool.

Considering compatibility, should we replace `language: system` with `language: golang`? Or is it better to add new configuration `actionlint-golang` like `actionlint-docker`? I'm not sure replacing it is ok. For example, some user may use `actionlint` by downloading it from releases page and they may not have Go environment. Is the `language: golang` fallbacks to system-installed `actionlint` binary when Go toolchain is not installed?

**Comment by rhysd** [comment]
Due to #297, this PR is not mergeable. Can we close this?

**Comment by rhysd** [comment]
One more point. pre-commit seems to install the binary using `go install ./...`. It installs **all** executable packages in this repository. It means, all unnecessary binaries such as [the generate scripts](https://github.com/rhysd/actionlint/tree/main/scripts) are built and installed as well on your machine. Is it OK? Does pre-commit sandbox the installation in some temporary directory? Otherwise it will pollute your `~/go/bin` with the unnecessary binaries.

**Comment by dokempf** [comment]
I guess one could argue how breaking the change is. I would not consider the requirement to update pre-commit to be too breaking. The fact that your existing local installation of `actionlint` is silently ignored after the change is a bit more troublesome. If you want to apply a very conservative philosophy, introducing a new `actionlint-golang` is a good choice.

**Comment by Freed-Wu** [comment]
> > I would recommend adding a pre-commit version constraint to .pre-commit-hooks.yml to enforce >=3.0.0.
>
> It makes sense.

Fixed.

```yaml
  minimum_pre_commit_version: 3.0.0
```

**Comment by rhysd** [comment]
@dokempf I may be too conservative. Since I'm not a user of pre-commit, I'd like to prioritize actual users' opinions. So I think changing the `language` config is OK.

In addition, I think it is good to add the classic `language: system` config as `actionlint-system` for those who don't have Go toolchain. They can continue to use the same environment with very small effort (changing pre-commit hook ID from `actionlint` to `actionlint-system`)

@Freed-Wu @dokempf Current configuration clones the HEAD of main branch, am I correct? If so, I think it is safer to fix the revision cloned by pre-commit to the latest tag name (currently it's [v1.6.24](https://github.com/rhysd/actionlint/tree/v1.6.24)). Is it possible?

**Comment by rhysd** [comment]
I understood that the revision is in `.pre-commit-config.yaml` hence it is set by users. So we don't need to set it.

https://pre-commit.com/#pre-commit-configyaml---repos

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
[v1.6.25](https://github.com/rhysd/actionlint/releases/tag/v1.6.25) was released.

**Comment by adamchainz** [comment]
I have just tried the new golang hook out on my client's project and it works well. It's 10x faster than the Docker one - taking a 0.91s runtime down to 0.09s. Thank you very much! 🤘

**Pull request merged**
