### PR TITLE
add rules discussion and discussion_comment

### PR DESCRIPTION
**Pull request by peaceiris**
Add new webhook events `discussion` and `discussion_comment`.

- discussion: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion
- discussion_comment: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion_comment

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you for adding this! When I implemented the rule, the `discussion` hook was not documented yet.

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
I'll release this soon.

**Comment by rhysd** [comment]
I released v1.4.3 including this.

**Comment by peaceiris** [comment]
It worked well! Thank you!

**Pull request merged**
