### PR TITLE
Support reusable workflows in the same repository

### PR DESCRIPTION
**Pull request by jsok**
Recently announced that support for referencing workflow in the same
repository at the checked out commit:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

### CODE REVIEW

**Comment by npalm** [comment]
+1

**Comment by ScottGuymer** [comment]
Yeah this has started to pop up for us as we take advantage of the new feature..

**Comment by npalm** [comment]
@@rhysd Really nice job this linter, prevents a lot of common mistakes. But since we start using the new GitHub featore for local workflows templates the linter is broken. Would you have time to check the PR?

**Comment by ScottGuymer** [comment]
@rhysd any possibility of getting this merged?

**Review by rhysd — APPROVED** [review]
Thank you!

**Pull request merged**
